Parameters:
  TargetEnvironment:
    Description: 'Examples can be dev, test or prod'
    Type: 'String'

Resources:
  WorkbookApiDomainMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties: 
      BasePath: workbook
      DomainName: {'Fn::ImportValue': !Sub 'focusmark-${TargetEnvironment}-apigw-customdomain'}
      RestApiId: {'Fn::ImportValue': !Sub 'focusmark-${TargetEnvironment}-apigw-workbookapi'}
      Stage: !Ref TargetEnvironment